spring:

  mail:
    smtp:
      auth: true
      starttls:
        required: true
        enable: true
      socketFactory:
        class: javax.net.ssl.SSLSocketFactory
        fallback: false
      port: 465
      socketFactoryPort: 465
    AdminMail:
      id: rtssogang@gmail.com
      password: ydqu rxru ozsa njrl

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://database-2.c7qmaqsga3re.ap-northeast-2.rds.amazonaws.com:3306/voting?createDatabaseIfNotExist=true     # DB 없으면 자동 생성
#    username: admin
#    password: asdf1234
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-2.c7qmaqsga3re.ap-northeast-2.rds.amazonaws.com:3306/voting?createDatabaseIfNotExist=true     # DB 없으면 자동 생성
    username: admin
    password: asdf1234

  jpa:
    database:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true   # 데이터 베이스 초기화 시점을 지연 (data.sql)
    properties:
      hibernate.format_sql: true
      hibernate.dialect : org.hibernate.dialect.MySQLDialect

  sql:      # (data.sql)
    init:
      mode : always

  server:
    port: 8080

JWT_TOKEN : 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA

